version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/services/ApiGateway/Dockerfile

  web.mvc:
    image: ${DOCKER_REGISTRY-}webmvc
    build:
      context: .
      dockerfile: src/services/Web.MVC/Web.Mvc/Dockerfile


  items.db:
    image: postgres

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: src/services/IdentityServer/Dockerfile

  items.api:
    image: ${DOCKER_REGISTRY-}itemsapi
    build:
      context: .
      dockerfile: src/services/Items.API/Dockerfile

volumes:
  postgres_data:



